/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package laboratorio__1.Semana_6;
import java.util.Random;
import java.util.Scanner;

import javax.swing.JTextField;


/**
 *
 * @author David
 */
public class GamplayFrame extends javax.swing.JFrame{
    
    //Arreglo de palabras
    public static String palabras[]={"casa","gato","perro","camisa","zapato","aeroplano","paracetamol","onomatopeya","ciudad"};

    
        
    //generador de numero random
    public static Random num = new Random();
    public static int seleccionID= num.nextInt(10);
    
    //Seleccion de palabra random
    public static String wordSeleccion= palabras[seleccionID];
    public static int lengthpalabra= wordSeleccion.length();
    
    //Creacion de palabras en blanco
    public static String blankword="";
    
    public static String letraingresada= "";
    
    public static boolean mostrar=false;
    
    public static boolean evaluar=false;
    
    
    public static String campoupdate="";
    
    public GamplayFrame() {
        initComponents();
        pantallatexto.setEditable(false);

        pantallatexto.setText(blankword);
        ingresoletra.setText(" ");
    
  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        pantallatexto = new javax.swing.JTextField();
        ingresoletra = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        oportunidades = new javax.swing.JTextField();
        textoshow = new java.awt.Label();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantallatexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pantallatexto.setText("Texto Aqui");
        pantallatexto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pantallatexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantallatextoActionPerformed(evt);
            }
        });

        ingresoletra.setText("jTextField2");
        ingresoletra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresoletraActionPerformed(evt);
            }
        });

        label1.setName(""); // NOI18N
        label1.setText("Ingrese una letra");

        oportunidades.setText("Oportunidades: n");

        textoshow.setAlignment(java.awt.Label.CENTER);
        textoshow.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textoshow.setText("¡ADIVINA!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ingresoletra, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(oportunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pantallatexto, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textoshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(textoshow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pantallatexto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingresoletra, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oportunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pantallatextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantallatextoActionPerformed
        this.setEnabled(false);
        
        
    }//GEN-LAST:event_pantallatextoActionPerformed

    private void ingresoletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresoletraActionPerformed
         String letra= ingresoletra.getText();
         System.out.println(letra);
         letraingresada=letra;
         evaluar=true;
         ingresoletra.setText(" ");
         
        
         if(evaluar==true){
             for(int j=0; j<=lengthpalabra-1; j++){
                char letraoriginal = wordSeleccion.charAt(j);
                String Sletraoriginal= Character.toString(letraoriginal);
                if(letraingresada.equalsIgnoreCase(Sletraoriginal)){
                    campoupdate+=Sletraoriginal;
                 
                }else{
                 campoupdate+=blankword.charAt(j);
                }
               }
             mostrar=true;
           }
         
           
        if(mostrar==true){
            pantallatexto.setText(campoupdate);
            mostrar=false;
        }
         
         
    }//GEN-LAST:event_ingresoletraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GamplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GamplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GamplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GamplayFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.out.println(wordSeleccion);
        int oportunidad= 5;
        //generador de palabra en blanco
   
        
        int i=0;
        while(i<=lengthpalabra-1){
            blankword+=("_"+" ");
            i++;
        }
     
        
        /*
        boolean ejecucionPrograma=true;
        while(ejecucionPrograma==true){
          
          
        }

        */
         
   
     
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamplayFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ingresoletra;
    private javax.swing.JDialog jDialog1;
    private java.awt.Label label1;
    private javax.swing.JTextField oportunidades;
    private javax.swing.JTextField pantallatexto;
    private java.awt.Label textoshow;
    // End of variables declaration//GEN-END:variables
}
